### ISSUE TITLE
Window content size 100% but some content is not visible

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material-addins#182]
A part of the window content is invisible. The size of that invisible content is the size of the window-toolbar (down of the widow).

I saw this by adding a scrollable content in the window like that :
```xml

<ui:style>
    .windowContent {
        max-height: 60vh;
        overflow: auto;
    }
</ui:style>

<ma:window.MaterialWindow ui:field="window" width="75%">
    <m:MaterialPanel styleName="{style.windowContent}">
        <!-- A lot of content -->
    </m:MaterialPanel>
</ma:window.MaterialWindow>
```

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/53288dcdb19229da3851ffb4b24f25f43b72560a

![window](https://cloud.githubusercontent.com/assets/3138071/21627532/6c423df6-d253-11e6-9365-1c2c2bfee976.gif)

**Comment by reofake** [comment]
This is good but not perfect, the size of the window toolbar is not fixed. If there is too much content on the toolbar it grows up (too long title, too much buttons...), for exemple the last window of your website on a phone screen.
That's why I posted [this other issue](https://github.com/GwtMaterialDesign/gwt-material-addins/issues/180) to possibly have a window size in function of the screen.
