### ISSUE TITLE
Autocomplete(TEXT) - Width of text field is not 100%.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#205]
On MaterialAutocomplete with type TEXT, it seems that the suggestbox field is not 100% occupied on autocomplete's container.

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/23363281/e6284ffa-fd34-11e6-954f-38dcd26aa97f.png)

Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/51ba75aff98ec36b66afdb4c0ee124319a551078

**Comment by washowasho** [comment]
This still appears to be open in rc4. MaterialAutoComplete type="TEXT" . Not taking the whole width of field after selecting a suggestion from AutoComplete.

**Comment by kevzlou7979** [comment]
![autucomplete-text-width](https://cloud.githubusercontent.com/assets/3138071/25333616/8366514a-291d-11e7-87f8-3b8a04c874b2.gif)

This seems to be fixed on 2.0-SNAPSHOT.
