### ISSUE TITLE
MaterialTimePicker - setting 24 Hour

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material-addins#226]
In my project I use Errai and set  "locale" to "pl_PL", and there is problems whith MaterialTimePicker when set to 24 Hour: 
1. Widget doesn't show 24 Hour MaterialTimePicer
2. When user click on initial value widget show actual Time (not initial time)
In http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#timepickers is also the same second problem, because after setting time, second click show the current time.

![timepickerr_error](https://cloud.githubusercontent.com/assets/608413/25238519/f7b50a92-25ed-11e7-9d27-2ef9fe2c4ab3.gif)

**Comment by kevzlou7979** [comment]
I think on latest SNAPSHOT this was solved already http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#timepickers

**Comment by matam** [comment]
Now I'm upgrade to the last snapshot, and still the same problem.
